// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ged.web;

import ged.web.LocalizadorController;
import java.io.Serializable;

privileged aspect LocalizadorController_Roo_Serializable {
    
    declare parents: LocalizadorController implements Serializable;
    
    private static final long LocalizadorController.serialVersionUID = 1L;
    
}
