// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ged.web;

import ged.web.LocalController;
import java.io.Serializable;

privileged aspect LocalController_Roo_Serializable {
    
    declare parents: LocalController implements Serializable;
    
    private static final long LocalController.serialVersionUID = 1L;
    
}
