// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ged.web;

import ged.web.PastasController;
import java.io.Serializable;

privileged aspect PastasController_Roo_Serializable {
    
    declare parents: PastasController implements Serializable;
    
    private static final long PastasController.serialVersionUID = 1L;
    
}
