// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ged.web;

import ged.web.PastaGrupoController;
import java.io.Serializable;

privileged aspect PastaGrupoController_Roo_Serializable {
    
    declare parents: PastaGrupoController implements Serializable;
    
    private static final long PastaGrupoController.serialVersionUID = 1L;
    
}
