// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ged.web;

import ged.web.PastaPropriedadesController;
import java.io.Serializable;

privileged aspect PastaPropriedadesController_Roo_Serializable {
    
    declare parents: PastaPropriedadesController implements Serializable;
    
    private static final long PastaPropriedadesController.serialVersionUID = 1L;
    
}
