// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ged.web;

import ged.web.TipoDadosController;
import java.io.Serializable;

privileged aspect TipoDadosController_Roo_Serializable {
    
    declare parents: TipoDadosController implements Serializable;
    
    private static final long TipoDadosController.serialVersionUID = 1L;
    
}
