// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ged.web;

import ged.web.TipoDadosController;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TipoDadosController_Roo_Configurable {
    
    declare @type: TipoDadosController: @Configurable;
    
}
