// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ged.web.converter;

import ged.web.converter.PastaGrupoConverter;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PastaGrupoConverter_Roo_Configurable {
    
    declare @type: PastaGrupoConverter: @Configurable;
    
}
