// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ged.domain.documentos;

import ged.domain.documentos.Local;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Local_Roo_Configurable {
    
    declare @type: Local: @Configurable;
    
}
